/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NstBadge {
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'error';
    }
    interface NstButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'outline' | 'ghost';
    }
    interface NstCard {
        /**
          * @default 'md'
         */
        "padding": 'sm' | 'md' | 'lg';
    }
    interface NstInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface NstSpinner {
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
export interface NstInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNstInputElement;
}
declare global {
    interface HTMLNstBadgeElement extends Components.NstBadge, HTMLStencilElement {
    }
    var HTMLNstBadgeElement: {
        prototype: HTMLNstBadgeElement;
        new (): HTMLNstBadgeElement;
    };
    interface HTMLNstButtonElement extends Components.NstButton, HTMLStencilElement {
    }
    var HTMLNstButtonElement: {
        prototype: HTMLNstButtonElement;
        new (): HTMLNstButtonElement;
    };
    interface HTMLNstCardElement extends Components.NstCard, HTMLStencilElement {
    }
    var HTMLNstCardElement: {
        prototype: HTMLNstCardElement;
        new (): HTMLNstCardElement;
    };
    interface HTMLNstInputElementEventMap {
        "inputChange": string;
        "inputFocus": void;
        "inputBlur": void;
    }
    interface HTMLNstInputElement extends Components.NstInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNstInputElementEventMap>(type: K, listener: (this: HTMLNstInputElement, ev: NstInputCustomEvent<HTMLNstInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNstInputElementEventMap>(type: K, listener: (this: HTMLNstInputElement, ev: NstInputCustomEvent<HTMLNstInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNstInputElement: {
        prototype: HTMLNstInputElement;
        new (): HTMLNstInputElement;
    };
    interface HTMLNstSpinnerElement extends Components.NstSpinner, HTMLStencilElement {
    }
    var HTMLNstSpinnerElement: {
        prototype: HTMLNstSpinnerElement;
        new (): HTMLNstSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "nst-badge": HTMLNstBadgeElement;
        "nst-button": HTMLNstButtonElement;
        "nst-card": HTMLNstCardElement;
        "nst-input": HTMLNstInputElement;
        "nst-spinner": HTMLNstSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface NstBadge {
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'error';
    }
    interface NstButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'outline' | 'ghost';
    }
    interface NstCard {
        /**
          * @default 'md'
         */
        "padding"?: 'sm' | 'md' | 'lg';
    }
    interface NstInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "name"?: string;
        "onInputBlur"?: (event: NstInputCustomEvent<void>) => void;
        "onInputChange"?: (event: NstInputCustomEvent<string>) => void;
        "onInputFocus"?: (event: NstInputCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface NstSpinner {
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface IntrinsicElements {
        "nst-badge": NstBadge;
        "nst-button": NstButton;
        "nst-card": NstCard;
        "nst-input": NstInput;
        "nst-spinner": NstSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nst-badge": LocalJSX.NstBadge & JSXBase.HTMLAttributes<HTMLNstBadgeElement>;
            "nst-button": LocalJSX.NstButton & JSXBase.HTMLAttributes<HTMLNstButtonElement>;
            "nst-card": LocalJSX.NstCard & JSXBase.HTMLAttributes<HTMLNstCardElement>;
            "nst-input": LocalJSX.NstInput & JSXBase.HTMLAttributes<HTMLNstInputElement>;
            "nst-spinner": LocalJSX.NstSpinner & JSXBase.HTMLAttributes<HTMLNstSpinnerElement>;
        }
    }
}
